In [41]:
import numpy as np

In [42]:
ar = np.array([1,2,-3,6,7,-10,88,43,-98,17,39,45])
ar

array([  1,   2,  -3,   6,   7, -10,  88,  43, -98,  17,  39,  45])

In [47]:
ar1 = np.array([4,5,9,10,23,-14,55,13])
ar = np.append(ar,ar1)

In [48]:
ar

array([  1,   2,  -3,   6,   7, -10,  88,  43, -98,  17,  39,  45,   4,
         5,   9,  10,  23, -14,  55,  13])

In [49]:
np.where(ar==9)

(array([14], dtype=int32),)

In [50]:
np.where(ar<0)

(array([ 2,  5,  8, 17], dtype=int32),)

In [51]:
ar[ar<0]

array([ -3, -10, -98, -14])

In [52]:
np.round(np.mean(ar),1)

12.1

In [55]:
ar_abs = np.absolute(ar)

In [56]:
ar_p = np.cbrt(ar_abs)

In [57]:
ar_p=np.round(ar_p,2)

In [59]:
ar_sq=np.sqrt(np.sum(ar_p))
ar_sq =int(ar_sq)

In [60]:
type(ar_sq)

int

In [61]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [63]:
import os

In [82]:
data = os.getcwd()

In [83]:
data

'C:\\Users\\Franek\\Desktop\\koło programistyczne'

In [77]:
os.listdir()

['.ipynb_checkpoints',
 'Koło zajecia 2.ipynb',
 'py-master',
 'py-master.zip',
 's01_e03_before FO (1).ipynb',
 's01_pd01.ipynb',
 's01_pd01.ipynb.txt',
 's01_pd02.ipynb',
 's01_pd03.csv',
 's01_pd03.ipynb',
 'Tygrysek_Kazimierz',
 'Untitled1.ipynb',
 'Wyzwanie.ipynb',
 'zajecia 6 frOs.ipynb']

In [78]:
os.listdir()[8]

's01_pd03.csv'

In [86]:
myFile = os.path.join(os.getcwd(), 's01_pd03.csv')
print(myFile)

C:\Users\Franek\Desktop\koło programistyczne\s01_pd03.csv


In [151]:
pd.read_csv(myFile, 's01_pd03.csv' )

C:\Users\Franek\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  if __name__ == '__main__':


salary;happiness
0            5222;94
1            3158;90
2            4973;68
3            7048;68
4            9407;75
5            7850;67
6            6687;68
7            8273;71
8            7679;76
9            6670;65
10           4027;98
11           6012;83
12           7393;55
13           6347;87
14           6778;59
15           9718;49
16           7135;77
17           6836;83
18           7261;88
19           6511;79
20           8610;49
21           6489;78
22           8281;71
23           7800;80
24           8367;80
25           4977;81
26           5366;87
27           6747;91
28           7357;56
29           5951;73
..               ...
470          5467;80
471          4225;81
472          2814;89
473         10530;55
474          6870;97
475          6981;86
476          4578;85
477          4917;95
478          4906;97
479          4404;93
480          8963;68
481          7361;67
482          5740;94
483          7284;87
484          5772;96
485          5246;93
486          6289;66
487          5617;82
488          8730;57
489          9497;37
490          7300;89
491          9004;52
492          5894;99
493          9144;49
494          8393;81
495          6291;92
496          4888;79
497          5435;83
498          9031;68
499          5543;87

[500 rows x 1 columns]

In [90]:
%matplotlib inline